"use client";
import { Star, RefreshCw, ChevronLeft, ChevronRight } from "lucide-react";
import { useCallback,useEffect,useState } from "react";
import { appointmentsApi,type Rating,type RatingPage } from "@/services/appointments";
import { remoteQueueApi,type Desk } from "@/services/remote-queue";
import { getUsers,type User } from "@/services/users";
import { formatTimestamp,personName } from "./appointment-utils";
const empty:RatingPage={items:[],total:0,page:0,size:20,stats:{total:0,average:0}};
export default function AppointmentRatingsPage(){
 const [data,setData]=useState(empty),[desks,setDesks]=useState<Desk[]>([]),[users,setUsers]=useState<User[]>([]);const [filters,setFilters]=useState({page:0,deskId:"",ratedUserId:"",from:"",to:""});const [loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback((signal?:AbortSignal)=>{setLoading(true);setError("");return appointmentsApi.ratings({...filters,size:20},signal).then(setData).catch(e=>{if(e instanceof Error&&e.name!=="AbortError")setError(e.message)}).finally(()=>setLoading(false))},[filters]);
 useEffect(()=>{const c=new AbortController();const timer=window.setTimeout(()=>void load(c.signal),0);return()=>{window.clearTimeout(timer);c.abort()}},[load]);useEffect(()=>{Promise.all([remoteQueueApi.desks(false),getUsers({page:0,size:500})]).then(([d,u])=>{setDesks(d.items||[]);setUsers(u)}).catch(()=>{})},[]);
 const set=(key:string,value:string|number)=>setFilters(x=>({...x,[key]:value,page:key==="page"?Number(value):0}));
 return <div className="space-y-5"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-extrabold">Đánh giá người tiếp nhận tại quầy</h1><p className="text-sm text-slate-500">Dữ liệu chỉ đọc từ các lịch hẹn</p></div><button className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Làm mới</button></header>
 <section className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input aria-label="Từ ngày" className="min-h-11 rounded-xl border px-3" onChange={e=>set("from",e.target.value)} type="date" value={filters.from}/><input aria-label="Đến ngày" className="min-h-11 rounded-xl border px-3" onChange={e=>set("to",e.target.value)} type="date" value={filters.to}/><select aria-label="Quầy" className="min-h-11 rounded-xl border px-3" onChange={e=>set("deskId",e.target.value)} value={filters.deskId}><option value="">Tất cả quầy</option>{desks.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select aria-label="Người được đánh giá" className="min-h-11 rounded-xl border px-3" onChange={e=>set("ratedUserId",e.target.value)} value={filters.ratedUserId}><option value="">Tất cả cán bộ</option>{users.map(u=><option key={u.id} value={u.id}>{u.name||u.username}</option>)}</select></section>
 <div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border bg-white p-5"><span className="text-sm text-slate-500">Tổng lượt đánh giá</span><strong className="mt-2 block text-3xl">{data.stats.total}</strong></article><article className="rounded-2xl border bg-white p-5"><span className="text-sm text-slate-500">Điểm trung bình</span><strong className="mt-2 flex items-center gap-2 text-3xl">{Number(data.stats.average||0).toFixed(1)}<Star className="fill-amber-400 text-amber-400"/></strong></article></div>
 <section className="overflow-hidden rounded-2xl border bg-white">{loading?<div className="h-64 animate-pulse bg-slate-100"/>:error?<div className="p-10 text-center text-red-700">{error}<br/><button className="mt-3 rounded-xl bg-red-700 px-4 py-2 text-white" onClick={()=>void load()}>Thử lại</button></div>:!data.items.length?<p className="p-12 text-center text-slate-500">Chưa có đánh giá phù hợp.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Người tiếp nhận","Quầy","Điểm","Nhận xét","Tiêu chí chi tiết","Người đánh giá","Ngày đánh giá","Mã lịch hẹn"].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{data.items.map((r:Rating)=><tr key={r.id}><td className="px-4 py-4 font-semibold">{personName(r.ratedUser)}</td><td className="px-4 py-4">{r.desk?.name||r.desk?.code||r.deskId||"—"}</td><td className="px-4 py-4"><strong>{r.score??r.rating??"—"}</strong> ★</td><td className="max-w-64 px-4 py-4">{r.comment||r.content||"—"}</td><td className="max-w-72 px-4 py-4"><Criteria value={r.criteria}/></td><td className="px-4 py-4">{personName(r.rater||r.user)}</td><td className="px-4 py-4">{formatTimestamp(r.createdAt)}</td><td className="px-4 py-4">{r.appointmentCode||r.appointmentId||"—"}</td></tr>)}</tbody></table></div>}<footer className="flex items-center justify-between border-t px-4 py-3 text-sm"><span>Tổng {data.total}</span><div className="flex items-center gap-2"><button className="rounded-lg border p-2 disabled:opacity-40" disabled={filters.page===0} onClick={()=>set("page",filters.page-1)}><ChevronLeft/></button><span>Trang {filters.page+1}</span><button className="rounded-lg border p-2 disabled:opacity-40" disabled={(filters.page+1)*data.size>=data.total} onClick={()=>set("page",filters.page+1)}><ChevronRight/></button></div></footer></section></div>
}
function Criteria({value}:{value:Rating["criteria"]}){if(!value)return <>—</>;if(Array.isArray(value))return <ul>{value.map((x,i)=><li key={i}>{x.label||x.name||`Tiêu chí ${i+1}`}: {String(x.score??x.value??"—")}</li>)}</ul>;return <ul>{Object.entries(value).map(([k,v])=><li key={k}>{k}: {String(v)}</li>)}</ul>}
